feat: Defined externally
TrioBrothers/js_hotblood pull request #8
Opened 2021-01-26 12:55 UTC by dlwlstks96

클래스 내 멤버 함수를 클래스 외부에서 정의

- 범위지정 연산자(::) 이용

2021-01-26 14:16 UTC, planepaper commented
ㅎㅎ PR 설명부분에 클래스 내 멤버 함수를 클래스 외부에서 정의했다고 올려줬는데

클래스 선언 부분에 구현했던 멤버 함수를 선언 바깥 쪽에 구현

이라는 식의 표현이 더 알맞을거 같네 ㅎㅎ

그리고 정말 잘 올려줬는데, 구현한 부분은 소스파일로 새로 만들어서 올리는게 좋아!
클래스 선언 헤더파일(.h)과 소스파일 이름(.cpp)을 동일하게해서 소스파일 쪽에 구현한 것들을 올려야해 ㅎㅎ
민규꺼에 내가 전에 피드백 해줘서 고쳐놓은 부분이 있는데, 그거 참고하면 좋을거같아!

수정해서 다시 커밋해줘~

2021-01-27 07:49 UTC, dlwlstks96 commented
소스 파일에 구현한 AccountHandler 클래스 코드를 헤더 파일로
추가 생성하였습니다~

2021-01-27 10:53 UTC, planepaper requested changes

2021-01-27 10:53 UTC, planepaper commented on Project1/project.cpp
> +};
헤더파일로 옮겼으면 소스파일 내의 선언내용은 지워줘야할거같아~

2021-01-27 11:50 UTC, merged